// <auto-generated />
namespace CRM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nml : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nml));
        
        string IMigrationMetadata.Id
        {
            get { return "201907021911159_nml"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
